spring:
  profiles:
    active:
      - "dev"
  jpa:
    properties:
      hibernate:
        generate_statistics: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram.http.server.requests: true
      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999